# Generated by Django 4.2.4 on 2023-08-31 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=25, unique=True)),
                ('problem', models.CharField(blank=True, max_length=255)),
                ('suggestion_test', models.CharField(blank=True, max_length=255)),
                ('medicine', models.CharField(blank=True, max_length=255)),
                ('patient_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
            ],
        ),
    ]
