# Generated by Django 4.2.4 on 2023-08-31 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('payment_mode', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('payment_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
