# Generated by Django 4.2.4 on 2023-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile/'),
        ),
    ]
