# Generated by Django 4.2.4 on 2023-08-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(default=None, max_length=250, upload_to='profile/'),
        ),
    ]
