# Generated by Django 4.2.4 on 2023-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='profile/'),
        ),
    ]
