# Generated by Django 4.2.4 on 2023-08-31 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
