# Generated by Django 4.2.4 on 2023-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_managers_remove_user_profile_user_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile/'),
        ),
    ]
