# Generated by Django 4.2.4 on 2023-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='null', max_length=50, unique=True),
        ),
    ]
