# Generated by Django 4.2.4 on 2023-09-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.appointment'),
        ),
    ]
