# Generated by Django 4.2.4 on 2023-09-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_patient_patient_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
